// Добавляет английский перевод (поле `en`) к каждому слову во всех наборах
// data/vocab/<slug>/index.json. Запуск: node scripts/merge-en.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VOCAB_DIR = path.join(__dirname, "..", "data", "vocab");

const T = {
  // Приветствия и фразы вежливости
  "halo": "hello",
  "hai": "hi",
  "selamat pagi": "good morning",
  "selamat siang": "good afternoon",
  "selamat sore": "good evening",
  "selamat malam": "good night",
  "selamat datang": "welcome",
  "selamat tinggal": "goodbye",
  "selamat jalan": "safe journey",
  "selamat tidur": "sleep well",
  "selamat makan": "enjoy your meal",
  "selamat ulang tahun": "happy birthday",
  "apa kabar": "how are you",
  "apa kabar?": "how are you?",
  "baik": "good / fine",
  "baik-baik saja": "I'm fine",
  "terima kasih": "thank you",
  "sama-sama": "you're welcome",
  "maaf": "sorry",
  "permisi": "excuse me",
  "tolong": "please / help",
  "silakan": "please / go ahead",
  "mohon": "please (formal)",
  "sampai jumpa": "see you",
  "sampai besok": "see you tomorrow",
  "sampai nanti": "see you later",
  "senang berkenalan": "nice to meet you",
  "Senang berkenalan dengan Anda": "Nice to meet you",
  "hati-hati": "be careful",
  "semangat": "go for it",
  "ayo": "let's go",
  "mari": "let's",
  "oke": "ok",
  "baiklah": "all right",
  "tidak apa-apa": "it's okay",

  // Местоимения
  "saya": "I",
  "aku": "I (informal)",
  "kamu": "you",
  "kau": "you (poetic)",
  "Anda": "you (formal)",
  "anda": "you (formal)",
  "engkau": "you (poetic)",
  "dia": "he / she",
  "ia": "he / she (formal)",
  "beliau": "he / she (very respectful)",
  "kita": "we (inclusive)",
  "kami": "we (exclusive)",
  "kalian": "you (plural)",
  "mereka": "they",
  "diri": "self",
  "diri sendiri": "oneself",

  // Вопросительные
  "apa": "what",
  "siapa": "who",
  "mana": "where / which",
  "di mana": "where",
  "ke mana": "where to",
  "dari mana": "where from",
  "kapan": "when",
  "mengapa": "why",
  "kenapa": "why (informal)",
  "bagaimana": "how",
  "berapa": "how many / how much",
  "yang mana": "which one",
  "apakah": "is (question particle)",

  // Указательные
  "ini": "this",
  "itu": "that",
  "sini": "here",
  "sana": "there",
  "situ": "there (near you)",
  "begini": "like this",
  "begitu": "like that",
  "seperti ini": "like this",
  "seperti itu": "like that",

  // Грамматика / частицы
  "tidak": "no / not",
  "tak": "not (short)",
  "bukan": "not (with noun)",
  "belum": "not yet",
  "sudah": "already",
  "telah": "already (formal)",
  "pernah": "ever",
  "masih": "still",
  "baru": "just / new",
  "akan": "will",
  "mau": "want / will",
  "ingin": "want",
  "hendak": "intend to",
  "sedang": "in the middle of",
  "lagi": "again / more",
  "harus": "must",
  "wajib": "obligatory",
  "perlu": "need",
  "butuh": "need",
  "boleh": "may",
  "bisa": "can",
  "dapat": "can / get",
  "mampu": "able",
  "jangan": "don't",
  "yang": "which / that",
  "ada": "there is",
  "adalah": "is / are",

  // Предлоги
  "di": "in / at",
  "ke": "to",
  "dari": "from",
  "pada": "at / on",
  "dengan": "with",
  "untuk": "for",
  "buat": "for (informal)",
  "oleh": "by",
  "tentang": "about",
  "tanpa": "without",
  "sampai": "until",
  "hingga": "until (formal)",
  "sejak": "since",
  "antara": "between",
  "melalui": "through",
  "terhadap": "toward",
  "kepada": "to (formal)",
  "atas": "above",
  "bawah": "below",
  "dalam": "in / inside / deep",
  "luar": "outside",
  "depan": "front",
  "belakang": "back",
  "samping": "side",
  "tengah": "middle",
  "sekitar": "around",
  "dekat": "near",
  "jauh": "far",

  // Союзы
  "dan": "and",
  "atau": "or",
  "tapi": "but",
  "tetapi": "but (formal)",
  "namun": "however",
  "karena": "because",
  "sebab": "because",
  "supaya": "so that",
  "agar": "so that",
  "kalau": "if / when",
  "jika": "if",
  "walaupun": "although",
  "meskipun": "although",
  "sebelum": "before",
  "sesudah": "after",
  "setelah": "after",
  "ketika": "when",
  "saat": "at the moment",
  "sambil": "while",
  "sementara": "while",
  "selama": "during",
  "lalu": "then",
  "kemudian": "then",
  "jadi": "so / become",
  "juga": "also",
  "saja": "only / just",
  "pun": "even",
  "bahkan": "moreover",
  "misalnya": "for example",
  "sebagai": "as",

  // Утверждение
  "ya": "yes",
  "iya": "yes (informal)",
  "betul": "correct",
  "benar": "right",
  "salah": "wrong",
  "tentu": "certainly",
  "tentu saja": "of course",
  "pasti": "surely",
  "mungkin": "maybe",
  "barangkali": "perhaps",
  "mustahil": "impossible",

  // Числа
  "nol": "zero",
  "satu": "one",
  "dua": "two",
  "tiga": "three",
  "empat": "four",
  "lima": "five",
  "enam": "six",
  "tujuh": "seven",
  "delapan": "eight",
  "sembilan": "nine",
  "sepuluh": "ten",
  "sebelas": "eleven",
  "dua belas": "twelve",
  "tiga belas": "thirteen",
  "empat belas": "fourteen",
  "lima belas": "fifteen",
  "enam belas": "sixteen",
  "tujuh belas": "seventeen",
  "delapan belas": "eighteen",
  "sembilan belas": "nineteen",
  "dua puluh": "twenty",
  "tiga puluh": "thirty",
  "empat puluh": "forty",
  "lima puluh": "fifty",
  "enam puluh": "sixty",
  "tujuh puluh": "seventy",
  "delapan puluh": "eighty",
  "sembilan puluh": "ninety",
  "seratus": "one hundred",
  "dua ratus": "two hundred",
  "lima ratus": "five hundred",
  "seribu": "one thousand",
  "sepuluh ribu": "ten thousand",
  "seratus ribu": "one hundred thousand",
  "sejuta": "one million",
  "semiliar": "one billion",
  "pertama": "first",
  "kedua": "second",
  "ketiga": "third",
  "keempat": "fourth",
  "kelima": "fifth",
  "terakhir": "last",
  "setengah": "half",
  "seperempat": "quarter",
  "kali": "times",
  "pasang": "pair",

  // Время
  "waktu": "time",
  "jam": "hour / clock",
  "menit": "minute",
  "detik": "second",
  "hari": "day",
  "minggu": "week",
  "bulan": "month / moon",
  "tahun": "year",
  "abad": "century",
  "zaman": "era",
  "masa": "period",
  "sekarang": "now",
  "nanti": "later",
  "tadi": "just now",
  "dulu": "before / used to",
  "dahulu": "long ago",
  "kemarin": "yesterday",
  "hari ini": "today",
  "besok": "tomorrow",
  "lusa": "day after tomorrow",
  "pagi": "morning",
  "siang": "noon / midday",
  "sore": "afternoon / evening",
  "malam": "night",
  "subuh": "dawn",
  "senja": "dusk",
  "tengah hari": "midday",
  "tengah malam": "midnight",
  "saat ini": "at this moment",
  "masa depan": "future",
  "masa lalu": "past",
  "minggu lalu": "last week",
  "minggu depan": "next week",
  "bulan lalu": "last month",
  "bulan depan": "next month",
  "tahun lalu": "last year",
  "tahun depan": "next year",
  "baru-baru ini": "recently",
  "akhir-akhir ini": "lately",
  "sebentar": "a moment",
  "sebentar lagi": "soon",
  "segera": "immediately",
  "buru-buru": "in a hurry",
  "awal": "beginning",
  "akhir": "end",
  "pertengahan": "middle",
  "sering": "often",
  "jarang": "rarely",
  "kadang-kadang": "sometimes",
  "selalu": "always",
  "tidak pernah": "never",
  "biasanya": "usually",

  // Дни / месяцы / сезоны
  "Senin": "Monday",
  "Selasa": "Tuesday",
  "Rabu": "Wednesday",
  "Kamis": "Thursday",
  "Jumat": "Friday",
  "Sabtu": "Saturday",
  "Minggu": "Sunday",
  "akhir pekan": "weekend",
  "Januari": "January",
  "Februari": "February",
  "Maret": "March",
  "April": "April",
  "Mei": "May",
  "Juni": "June",
  "Juli": "July",
  "Agustus": "August",
  "September": "September",
  "Oktober": "October",
  "November": "November",
  "Desember": "December",
  "musim": "season",
  "musim hujan": "rainy season",
  "musim kemarau": "dry season",
  "musim panas": "summer",
  "musim dingin": "winter",
  "musim semi": "spring",
  "musim gugur": "autumn",

  // Семья / люди
  "keluarga": "family",
  "orang tua": "parents",
  "ayah": "father",
  "bapak": "father / sir",
  "ibu": "mother / ma'am",
  "mama": "mom",
  "papa": "dad",
  "anak": "child",
  "anak laki-laki": "son",
  "anak perempuan": "daughter",
  "putra": "son (formal)",
  "putri": "daughter (formal)",
  "kakak": "older sibling",
  "abang": "older brother",
  "adik": "younger sibling",
  "saudara": "brother / relative",
  "saudari": "sister",
  "kakek": "grandfather",
  "nenek": "grandmother",
  "paman": "uncle",
  "bibi": "aunt",
  "om": "uncle (casual)",
  "tante": "aunt (casual)",
  "sepupu": "cousin",
  "suami": "husband",
  "istri": "wife",
  "pasangan": "partner",
  "mertua": "parent-in-law",
  "menantu": "son / daughter-in-law",
  "cucu": "grandchild",
  "keponakan": "nephew / niece",
  "teman": "friend",
  "sahabat": "best friend",
  "pacar": "boyfriend / girlfriend",
  "kenalan": "acquaintance",
  "tetangga": "neighbor",
  "tamu": "guest",
  "orang": "person",
  "laki-laki": "man",
  "pria": "man (formal)",
  "perempuan": "woman",
  "wanita": "woman (formal)",
  "cowok": "guy (slang)",
  "cewek": "girl (slang)",
  "anak-anak": "children",
  "remaja": "teenager",
  "dewasa": "adult",
  "bayi": "baby",
  "balita": "toddler",
  "tua": "old",
  "muda": "young",
  "nama": "name",
  "umur": "age",
  "usia": "age (formal)",
  "alamat": "address",
  "nomor telepon": "phone number",

  // Тело
  "tubuh": "body",
  "badan": "body",
  "kepala": "head",
  "rambut": "hair",
  "wajah": "face",
  "muka": "face",
  "dahi": "forehead",
  "mata": "eye",
  "alis": "eyebrow",
  "bulu mata": "eyelash",
  "hidung": "nose",
  "pipi": "cheek",
  "telinga": "ear",
  "kuping": "ear (casual)",
  "mulut": "mouth",
  "bibir": "lip",
  "gigi": "tooth",
  "lidah": "tongue",
  "dagu": "chin",
  "leher": "neck",
  "tenggorokan": "throat",
  "bahu": "shoulder",
  "lengan": "arm",
  "siku": "elbow",
  "tangan": "hand",
  "jari": "finger",
  "ibu jari": "thumb",
  "kuku": "nail",
  "telapak tangan": "palm",
  "dada": "chest",
  "perut": "stomach",
  "pinggang": "waist",
  "pinggul": "hip",
  "punggung": "back",
  "kaki": "leg / foot",
  "paha": "thigh",
  "lutut": "knee",
  "betis": "calf",
  "telapak kaki": "sole",
  "kulit": "skin",
  "darah": "blood",
  "tulang": "bone",
  "otot": "muscle",
  "jantung": "heart",
  "hati": "liver / soul",
  "paru-paru": "lungs",
  "otak": "brain",
  "ginjal": "kidney",
  "perasaan": "feeling",
  "pikiran": "thought / mind",
  "ingatan": "memory",
  "mimpi": "dream",

  // Здоровье
  "sehat": "healthy",
  "sakit": "sick / painful",
  "penyakit": "disease",
  "demam": "fever",
  "pilek": "runny nose",
  "batuk": "cough",
  "flu": "flu",
  "pusing": "dizzy",
  "sakit kepala": "headache",
  "sakit perut": "stomachache",
  "sakit gigi": "toothache",
  "luka": "wound",
  "obat": "medicine",
  "vitamin": "vitamin",
  "istirahat": "rest",
  "tidur": "sleep",
  "bangun": "wake up",
  "lelah": "tired",
  "capek": "tired (informal)",
  "lapar": "hungry",
  "kenyang": "full",
  "haus": "thirsty",
  "mengantuk": "sleepy",

  // Дом
  "rumah": "house",
  "kamar": "room",
  "ruang tamu": "living room",
  "kamar tidur": "bedroom",
  "kamar mandi": "bathroom",
  "dapur": "kitchen",
  "halaman": "yard",
  "garasi": "garage",
  "balkon": "balcony",
  "atap": "roof",
  "lantai": "floor",
  "dinding": "wall",
  "pintu": "door",
  "jendela": "window",
  "tangga": "stairs",
  "pagar": "fence",
  "kunci": "key",
  "meja": "table",
  "kursi": "chair",
  "sofa": "sofa",
  "tempat tidur": "bed",
  "kasur": "mattress",
  "bantal": "pillow",
  "selimut": "blanket",
  "lemari": "cupboard",
  "rak": "shelf",
  "laci": "drawer",
  "lampu": "lamp",
  "cermin": "mirror",
  "jam dinding": "wall clock",
  "kipas angin": "fan",
  "AC": "air conditioner",
  "TV": "TV",
  "kulkas": "fridge",
  "kompor": "stove",
  "oven": "oven",
  "mesin cuci": "washing machine",
  "panci": "pot",
  "wajan": "frying pan",
  "piring": "plate",
  "mangkuk": "bowl",
  "gelas": "glass",
  "cangkir": "cup",
  "sendok": "spoon",
  "garpu": "fork",
  "pisau": "knife",
  "sumpit": "chopsticks",
  "tisu": "tissue",
  "sabun": "soap",
  "sampo": "shampoo",
  "handuk": "towel",
  "sikat gigi": "toothbrush",
  "pasta gigi": "toothpaste",
  "sisir": "comb",

  // Еда
  "makanan": "food",
  "minuman": "drink",
  "sarapan": "breakfast",
  "makan siang": "lunch",
  "makan malam": "dinner",
  "makanan ringan": "snack",
  "camilan": "snack",
  "nasi": "rice (cooked)",
  "beras": "rice (uncooked)",
  "roti": "bread",
  "mie": "noodles",
  "sup": "soup",
  "sayur": "vegetable",
  "sayuran": "vegetables",
  "buah": "fruit",
  "daging": "meat",
  "ikan": "fish",
  "ayam": "chicken / rooster",
  "sapi": "beef / cow",
  "kambing": "goat",
  "babi": "pork / pig",
  "udang": "shrimp",
  "cumi": "squid",
  "telur": "egg",
  "susu": "milk",
  "keju": "cheese",
  "mentega": "butter",
  "minyak": "oil",
  "gula": "sugar",
  "garam": "salt",
  "lada": "pepper",
  "merica": "peppercorn",
  "bumbu": "spices",
  "kecap": "soy sauce",
  "sambal": "chili paste",
  "saus": "sauce",
  "cuka": "vinegar",
  "tepung": "flour",
  "kue": "cake",
  "permen": "candy",
  "cokelat": "chocolate / brown",
  "es krim": "ice cream",
  "madu": "honey",
  "selai": "jam",
  "nasi goreng": "fried rice",
  "mie goreng": "fried noodles",
  "sate": "satay",
  "rendang": "rendang",
  "soto": "soto soup",
  "bakso": "meatballs",
  "gado-gado": "gado-gado",
  "rasa": "taste",
  "enak": "delicious",
  "lezat": "tasty",
  "sedap": "delicious",
  "manis": "sweet",
  "asam": "sour",
  "asin": "salty",
  "pahit": "bitter",
  "pedas": "spicy",
  "gurih": "savory",
  "hambar": "bland",

  // Напитки
  "air": "water",
  "air putih": "drinking water",
  "es": "ice",
  "teh": "tea",
  "kopi": "coffee",
  "jus": "juice",
  "bir": "beer",
  "anggur": "wine / grape",
  "minuman keras": "liquor",
  "soda": "soda",
  "kelapa muda": "young coconut",

  // Фрукты/овощи
  "apel": "apple",
  "jeruk": "orange",
  "pisang": "banana",
  "mangga": "mango",
  "nanas": "pineapple",
  "semangka": "watermelon",
  "melon": "melon",
  "stroberi": "strawberry",
  "durian": "durian",
  "pepaya": "papaya",
  "kelapa": "coconut",
  "alpukat": "avocado",
  "pir": "pear",
  "rambutan": "rambutan",
  "manggis": "mangosteen",
  "salak": "snake fruit",
  "lemon": "lemon",
  "tomat": "tomato",
  "kentang": "potato",
  "wortel": "carrot",
  "mentimun": "cucumber",
  "terong": "eggplant",
  "bayam": "spinach",
  "kangkung": "water spinach",
  "cabai": "chili",
  "bawang merah": "shallot",
  "bawang putih": "garlic",
  "jahe": "ginger",
  "kunyit": "turmeric",
  "serai": "lemongrass",
  "jagung": "corn",
  "kacang": "nut / bean",
  "tahu": "to know / tofu",
  "tempe": "tempeh",

  // Одежда
  "pakaian": "clothing",
  "baju": "shirt / clothing",
  "kemeja": "shirt",
  "kaos": "t-shirt",
  "celana": "pants",
  "celana pendek": "shorts",
  "celana panjang": "long pants",
  "rok": "skirt",
  "gaun": "dress",
  "jaket": "jacket",
  "mantel": "coat",
  "jas": "suit / jacket",
  "dasi": "tie",
  "topi": "hat",
  "sepatu": "shoes",
  "sandal": "sandals",
  "kaus kaki": "socks",
  "sarung tangan": "gloves",
  "syal": "scarf",
  "ikat pinggang": "belt",
  "jam tangan": "wristwatch",
  "kacamata": "glasses",
  "tas": "bag",
  "ransel": "backpack",
  "dompet": "wallet",
  "cincin": "ring",
  "gelang": "bracelet",
  "kalung": "necklace",
  "anting": "earrings",
  "ukuran": "size",

  // Животные
  "binatang": "animal",
  "hewan": "animal",
  "anjing": "dog",
  "kucing": "cat",
  "kerbau": "buffalo",
  "kuda": "horse",
  "bebek": "duck",
  "burung": "bird",
  "ular": "snake",
  "katak": "frog",
  "kura-kura": "turtle",
  "monyet": "monkey",
  "tikus": "mouse / rat",
  "kelinci": "rabbit",
  "harimau": "tiger",
  "gajah": "elephant",
  "singa": "lion",
  "beruang": "bear",
  "serigala": "wolf",
  "rusa": "deer",
  "buaya": "crocodile",
  "hiu": "shark",
  "lumba-lumba": "dolphin",
  "paus": "whale",
  "kupu-kupu": "butterfly",
  "lebah": "bee",
  "semut": "ant",
  "nyamuk": "mosquito",
  "lalat": "fly",
  "laba-laba": "spider",
  "cecak": "gecko",

  // Природа
  "alam": "nature",
  "langit": "sky",
  "awan": "cloud",
  "matahari": "sun",
  "bintang": "star",
  "hujan": "rain",
  "salju": "snow",
  "angin": "wind",
  "badai": "storm",
  "petir": "thunder",
  "pelangi": "rainbow",
  "kabut": "fog",
  "embun": "dew",
  "panas": "hot",
  "dingin": "cold",
  "sejuk": "cool",
  "hangat": "warm",
  "lembap": "humid",
  "cuaca": "weather",
  "gunung": "mountain",
  "bukit": "hill",
  "lembah": "valley",
  "sungai": "river",
  "danau": "lake",
  "laut": "sea",
  "samudra": "ocean",
  "pantai": "beach",
  "ombak": "wave",
  "pulau": "island",
  "pasir": "sand",
  "batu": "stone",
  "tanah": "land / soil",
  "lumpur": "mud",
  "api": "fire",
  "asap": "smoke",
  "pohon": "tree",
  "hutan": "forest",
  "kayu": "wood",
  "daun": "leaf",
  "bunga": "flower",
  "rumput": "grass",
  "akar": "root",
  "biji": "seed",
  "ranting": "branch",
  "sawah": "rice field",
  "ladang": "field",
  "kebun": "garden",

  // Город / места
  "kota": "city",
  "desa": "village",
  "kampung": "hamlet",
  "daerah": "district",
  "wilayah": "region",
  "negara": "country",
  "ibu kota": "capital",
  "dunia": "world",
  "Indonesia": "Indonesia",
  "Rusia": "Russia",
  "Jakarta": "Jakarta",
  "Bali": "Bali",
  "Moskow": "Moscow",
  "tempat": "place",
  "lokasi": "location",
  "jalan": "road / street",
  "gang": "alley",
  "simpang": "intersection",
  "lampu lalu lintas": "traffic light",
  "jembatan": "bridge",
  "taman": "park",
  "lapangan": "field / square",
  "pasar": "market",
  "toko": "shop",
  "warung": "stall",
  "supermarket": "supermarket",
  "mal": "mall",
  "kantor": "office",
  "sekolah": "school",
  "universitas": "university",
  "rumah sakit": "hospital",
  "klinik": "clinic",
  "apotek": "pharmacy",
  "bank": "bank",
  "kantor pos": "post office",
  "stasiun": "station",
  "bandara": "airport",
  "pelabuhan": "port",
  "terminal": "terminal",
  "halte": "bus stop",
  "restoran": "restaurant",
  "kafe": "cafe",
  "hotel": "hotel",
  "museum": "museum",
  "perpustakaan": "library",
  "gereja": "church",
  "masjid": "mosque",
  "kuil": "temple",
  "pura": "Balinese temple",
  "kuburan": "cemetery",
  "polisi": "police",
  "kantor polisi": "police station",
  "pemadam kebakaran": "fire department",

  // Транспорт
  "kendaraan": "vehicle",
  "mobil": "car",
  "motor": "motorbike",
  "sepeda": "bicycle",
  "bus": "bus",
  "kereta api": "train",
  "pesawat": "airplane",
  "kapal": "ship",
  "perahu": "boat",
  "taksi": "taxi",
  "ojek": "motorbike taxi",
  "becak": "pedicab",
  "truk": "truck",
  "sopir": "driver",
  "penumpang": "passenger",
  "tiket": "ticket",
  "perjalanan": "trip",
  "liburan": "vacation",
  "wisata": "tourism",
  "turis": "tourist",
  "peta": "map",
  "koper": "suitcase",
  "paspor": "passport",
  "visa": "visa",
  "bahan bakar": "fuel",
  "bensin": "gasoline",
  "parkir": "parking",
  "macet": "traffic jam",

  // Работа
  "pekerjaan": "job",
  "kerja": "work",
  "tugas": "task",
  "proyek": "project",
  "rapat": "meeting",
  "pertemuan": "meeting",
  "perusahaan": "company",
  "bos": "boss",
  "atasan": "superior",
  "rekan": "colleague",
  "kolega": "colleague",
  "klien": "client",
  "pelanggan": "customer",
  "gaji": "salary",
  "upah": "wage",
  "guru": "teacher",
  "dosen": "lecturer",
  "murid": "pupil",
  "siswa": "student",
  "mahasiswa": "university student",
  "dokter": "doctor",
  "perawat": "nurse",
  "pengacara": "lawyer",
  "tentara": "soldier",
  "petani": "farmer",
  "nelayan": "fisherman",
  "pedagang": "trader",
  "penjual": "seller",
  "pembeli": "buyer",
  "koki": "chef",
  "pelayan": "waiter",
  "pilot": "pilot",
  "insinyur": "engineer",
  "programmer": "programmer",
  "seniman": "artist",
  "musisi": "musician",
  "penulis": "writer",
  "wartawan": "journalist",
  "fotografer": "photographer",
  "ibu rumah tangga": "housewife",
  "pensiunan": "retiree",
  "pengangguran": "unemployed",

  // Деньги
  "uang": "money",
  "rupiah": "rupiah",
  "dolar": "dollar",
  "rubel": "ruble",
  "harga": "price",
  "diskon": "discount",
  "gratis": "free",
  "mahal": "expensive",
  "murah": "cheap",
  "kaya": "rich",
  "miskin": "poor",
  "untung": "profit",
  "rugi": "loss",
  "kartu kredit": "credit card",
  "rekening": "account",
  "transfer": "transfer",
  "tunai": "cash",
  "kembalian": "change",
  "kuitansi": "receipt",
  "pajak": "tax",
  "hutang": "debt",
  "pinjaman": "loan",

  // Учёба
  "pendidikan": "education",
  "pelajaran": "lesson",
  "kelas": "class",
  "buku": "book",
  "buku tulis": "notebook",
  "pulpen": "pen",
  "pensil": "pencil",
  "penghapus": "eraser",
  "penggaris": "ruler",
  "papan tulis": "blackboard",
  "ujian": "exam",
  "tes": "test",
  "soal": "question",
  "jawaban": "answer",
  "nilai": "grade / value",
  "ijazah": "diploma",
  "gelar": "degree",
  "beasiswa": "scholarship",
  "tugas rumah": "homework",
  "PR": "homework",
  "kamus": "dictionary",
  "bahasa": "language",
  "kata": "word",
  "kalimat": "sentence",
  "huruf": "letter",
  "angka": "number",

  // Цвета
  "warna": "color",
  "merah": "red",
  "hijau": "green",
  "biru": "blue",
  "kuning": "yellow",
  "hitam": "black",
  "putih": "white",
  "abu-abu": "gray",
  "ungu": "purple",
  "oranye": "orange",
  "jingga": "orange",
  "merah muda": "pink",
  "perak": "silver",
  "emas": "gold",

  // Глаголы
  "pergi": "go",
  "datang": "come",
  "kembali": "return",
  "pulang": "go home",
  "masuk": "enter",
  "keluar": "exit",
  "naik": "go up / board",
  "turun": "go down / get off",
  "lewat": "pass by",
  "berjalan": "walk",
  "jalan-jalan": "stroll",
  "berlari": "run",
  "lari": "run",
  "berenang": "swim",
  "terbang": "fly",
  "duduk": "sit",
  "berdiri": "stand",
  "berbaring": "lie down",
  "makan": "eat",
  "minum": "drink",
  "masak": "cook",
  "memasak": "to cook",
  "membeli": "to buy",
  "beli": "buy",
  "menjual": "to sell",
  "jual": "sell",
  "membayar": "to pay",
  "bayar": "pay",
  "menerima": "to receive",
  "terima": "receive",
  "mengembalikan": "to return (something)",
  "melihat": "to see",
  "lihat": "look",
  "menonton": "to watch",
  "memperhatikan": "pay attention",
  "mendengar": "to hear",
  "dengar": "listen",
  "mendengarkan": "to listen to",
  "berbicara": "to speak",
  "bicara": "talk",
  "ngomong": "talk (informal)",
  "berkata": "to say",
  "mengatakan": "to say",
  "menjawab": "to answer",
  "bertanya": "to ask",
  "memanggil": "to call",
  "membaca": "to read",
  "menulis": "to write",
  "mencatat": "note down",
  "menggambar": "to draw",
  "mencari": "to search",
  "menemukan": "to find",
  "kehilangan": "to lose",
  "mengambil": "to take",
  "memberikan": "to give",
  "memberi": "give",
  "membawa": "to bring",
  "mengirim": "to send",
  "mengantar": "to escort / deliver",
  "membuka": "to open",
  "menutup": "to close",
  "memulai": "to start",
  "mulai": "start",
  "mengakhiri": "to end",
  "selesai": "finished",
  "beristirahat": "to rest",
  "mencuci": "to wash",
  "membersihkan": "to clean",
  "menyapu": "to sweep",
  "membantu": "to help",
  "menolong": "to help",
  "berpikir": "to think",
  "memikirkan": "to think about",
  "percaya": "to believe",
  "mengerti": "to understand",
  "memahami": "to understand",
  "mengetahui": "to know (formal)",
  "ingat": "remember",
  "mengingat": "to remember",
  "lupa": "forget",
  "melupakan": "to forget",
  "suka": "like",
  "menyukai": "to like",
  "cinta": "love",
  "mencintai": "to love",
  "sayang": "love / pity",
  "benci": "hate",
  "marah": "angry",
  "senang": "happy",
  "gembira": "cheerful",
  "bahagia": "happy",
  "sedih": "sad",
  "takut": "afraid",
  "kaget": "shocked",
  "terkejut": "surprised",
  "malu": "shy",
  "bangga": "proud",
  "kecewa": "disappointed",
  "bingung": "confused",
  "kesal": "annoyed",
  "menangis": "cry",
  "tertawa": "laugh",
  "tersenyum": "smile",
  "merasa": "to feel",
  "hidup": "live / alive",
  "mati": "die / dead",
  "lahir": "be born",
  "meninggal": "pass away",
  "menikah": "get married",
  "bertemu": "to meet",
  "ketemu": "meet (informal)",
  "berpisah": "part / separate",
  "menunggu": "to wait",
  "tunggu": "wait",
  "terlambat": "to be late",
  "bermain": "to play",
  "main": "play",
  "menari": "to dance",
  "menyanyi": "to sing",
  "bernyanyi": "to sing",
  "menggunakan": "to use",
  "memakai": "to wear / use",
  "pakai": "wear",
  "mencoba": "to try",
  "berusaha": "to try / endeavor",
  "berhasil": "succeed",
  "gagal": "fail",
  "menang": "win",
  "kalah": "lose",
  "mengubah": "to change",
  "mengganti": "to replace",
  "menambah": "to add",
  "mengurangi": "to reduce",
  "memperbaiki": "to repair",
  "merusak": "to damage",
  "membuat": "to make",
  "bikin": "make (informal)",
  "melakukan": "to do",
  "mempunyai": "to have",
  "punya": "have",
  "memiliki": "to own",
  "menjadi": "to become",
  "mengajar": "to teach",
  "mengajari": "to instruct",
  "belajar": "to learn",
  "mempelajari": "to study",
  "berlatih": "to practice",
  "berolahraga": "exercise",
  "berlibur": "to vacation",
  "bersantai": "to relax",
  "berbohong": "to lie",
  "jujur": "honest",
  "mencuri": "to steal",
  "menipu": "to deceive",
  "mengundang": "to invite",
  "menolak": "to refuse",
  "menyetujui": "to agree to",
  "setuju": "agree",
  "mengizinkan": "to allow",
  "melarang": "to forbid",
  "memesan": "to order",
  "pesan": "order / message",
  "mengirimkan": "to send",
  "menelpon": "to call",
  "menelepon": "to call (formal)",
  "menjelaskan": "to explain",
  "memilih": "to choose",
  "membayangkan": "to imagine",
  "bermimpi": "to dream",
  "menghitung": "to count",
  "menjaga": "to guard",
  "melindungi": "to protect",
  "menyelamatkan": "to save",
  "menyembunyikan": "to hide",
  "berhenti": "to stop",
  "melanjutkan": "to continue",
  "lanjut": "continue",

  // Прилагательные
  "bagus": "good",
  "jelek": "bad / ugly",
  "buruk": "bad",
  "hebat": "great",
  "keren": "cool",
  "biasa": "ordinary",
  "luar biasa": "extraordinary",
  "besar": "big",
  "kecil": "small",
  "panjang": "long",
  "pendek": "short",
  "tinggi": "tall / high",
  "rendah": "low",
  "lebar": "wide",
  "sempit": "narrow",
  "tebal": "thick",
  "tipis": "thin",
  "dangkal": "shallow",
  "banyak": "many",
  "sedikit": "few",
  "cukup": "enough",
  "kurang": "less",
  "lama": "long time / old",
  "kuno": "ancient",
  "modern": "modern",
  "cepat": "fast",
  "lambat": "slow",
  "pelan": "slow",
  "mudah": "easy",
  "gampang": "easy",
  "susah": "difficult",
  "sulit": "difficult",
  "ringan": "light",
  "berat": "heavy",
  "penuh": "full",
  "kosong": "empty",
  "kering": "dry",
  "basah": "wet",
  "terang": "bright",
  "gelap": "dark",
  "cerah": "sunny",
  "mendung": "cloudy",
  "indah": "beautiful",
  "cantik": "pretty",
  "ganteng": "handsome",
  "tampan": "handsome",
  "kuat": "strong",
  "lemah": "weak",
  "segar": "fresh",
  "bersih": "clean",
  "kotor": "dirty",
  "rapi": "tidy",
  "berantakan": "messy",
  "ramai": "crowded",
  "sepi": "quiet",
  "ramah": "friendly",
  "sopan": "polite",
  "kasar": "rude",
  "pintar": "smart",
  "pandai": "clever",
  "cerdas": "intelligent",
  "bodoh": "stupid",
  "rajin": "diligent",
  "malas": "lazy",
  "berani": "brave",
  "penakut": "cowardly",
  "baik hati": "kind",
  "jahat": "evil",
  "sabar": "patient",
  "gemuk": "fat",
  "kurus": "thin",
  "langsing": "slim",
  "penting": "important",
  "menarik": "interesting",
  "membosankan": "boring",
  "lucu": "funny",
  "serius": "serious",
  "aman": "safe",
  "bahaya": "danger",
  "berbahaya": "dangerous",
  "nyaman": "comfortable",
  "tenang": "calm",
  "ribut": "noisy",
  "berisik": "noisy",
  "bising": "noisy",
  "asli": "original",
  "palsu": "fake",

  // Модификаторы
  "sangat": "very",
  "sekali": "very",
  "amat": "extremely",
  "terlalu": "too",
  "agak": "a bit",
  "lebih": "more",
  "paling": "most",
  "lebih baik": "better",
  "paling baik": "best",
  "sama": "same",
  "berbeda": "different",
  "beda": "difference",
  "mirip": "similar",
  "khusus": "special",
  "umum": "general",
  "khas": "characteristic",
  "spesial": "special",
  "bersama": "together",
  "sendiri": "alone / self",
  "sendirian": "by oneself",

  // Технологии
  "internet": "internet",
  "wifi": "wifi",
  "komputer": "computer",
  "laptop": "laptop",
  "ponsel": "cell phone",
  "hp": "phone",
  "telepon": "phone",
  "email": "email",
  "aplikasi": "app",
  "situs": "website",
  "media sosial": "social media",
  "foto": "photo",
  "gambar": "picture",
  "video": "video",
  "film": "movie",
  "lagu": "song",
  "musik": "music",
  "berita": "news",
  "informasi": "information",
  "data": "data",

  // Религия
  "agama": "religion",
  "Tuhan": "God",
  "doa": "prayer",
  "berdoa": "to pray",
  "puasa": "fasting",
  "Islam": "Islam",
  "Kristen": "Christianity",
  "Hindu": "Hinduism",
  "Buddha": "Buddhism",

  // Праздники
  "selamat hari raya": "happy holiday",
  "Lebaran": "Eid al-Fitr",
  "Natal": "Christmas",
  "Tahun Baru": "New Year",
  "hari libur": "holiday",
  "pesta": "party",
  "ulang tahun": "birthday",
  "hadiah": "gift",
  "kado": "gift",
  "kue ulang tahun": "birthday cake",
  "lilin": "candle",
  "balon": "balloon",

  // Абстрактные
  "pertanyaan": "question",
  "masalah": "problem",
  "solusi": "solution",
  "ide": "idea",
  "rencana": "plan",
  "tujuan": "goal",
  "harapan": "hope",
  "cita-cita": "ambition",
  "alasan": "reason",
  "hasil": "result",
  "contoh": "example",
  "fakta": "fact",
  "kebenaran": "truth",
  "kebohongan": "lie",
  "kabar": "news",
  "cerita": "story",
  "kisah": "tale",
  "pendapat": "opinion",
  "pengalaman": "experience",
  "kesempatan": "opportunity",
  "pilihan": "choice",
  "perubahan": "change",
  "kehidupan": "life",
  "kematian": "death",
  "kelahiran": "birth",
  "pernikahan": "marriage",

  // Фразы
  "siapa namamu": "what's your name",
  "siapa nama Anda": "what is your name (formal)",
  "Siapa nama Anda?": "What is your name?",
  "berapa umurmu": "how old are you",
  "dari mana asalmu": "where are you from",
  "kamu tinggal di mana": "where do you live",
  "bisa berbicara bahasa Indonesia": "can you speak Indonesian",
  "saya tidak mengerti": "I don't understand",
  "saya mengerti": "I understand",
  "tolong ulangi": "please repeat",
  "tolong bicara pelan-pelan": "please speak slowly",
  "apa artinya": "what does it mean",
  "bagaimana mengatakannya": "how do I say it",
  "saya tidak tahu": "I don't know",
  "saya tidak yakin": "I'm not sure",
  "tidak masalah": "no problem",
  "jangan khawatir": "don't worry",
  "tenang saja": "just relax",
  "tidak masalah bagi saya": "no problem for me",
  "saya setuju": "I agree",
  "saya tidak setuju": "I disagree",
  "menurut saya": "in my opinion",
  "saya rasa": "I think",
  "saya kira": "I suppose",

  // Из урока 1 / стартовых наборов (фразы)
  "Saya Andrei.": "I am Andrei.",
  "Saya orang Rusia.": "I am Russian.",
  "Saya mahasiswa.": "I am a student.",
  "Dia guru.": "He / she is a teacher.",
  "Kami teman.": "We are friends.",
  "Nama saya Andrei.": "My name is Andrei.",
  "Saya dari Rusia.": "I am from Russia.",
  "Anda dari mana?": "Where are you from?",
};

// Нормализованная карта: ключ в lower-case, без хвостового "?"
const TN = {};
for (const [k, v] of Object.entries(T)) {
  const norm = k.toLowerCase().replace(/[?.!]$/u, "").trim();
  if (!TN[norm]) TN[norm] = v;
}

function lookup(id) {
  if (T[id]) return T[id];
  const norm = id.toLowerCase().replace(/[?.!]$/u, "").trim();
  const en = TN[norm];
  if (!en) return undefined;
  // Если оригинал начинается с заглавной — английский тоже с большой,
  // плюс сохраняем хвостовой "?" если был.
  let out = en;
  if (/^[A-ZА-ЯA-ZЁ]/u.test(id) || /^[A-Z]/u.test(id)) {
    out = out.charAt(0).toUpperCase() + out.slice(1);
  }
  const trailing = id.match(/[?.!]$/u);
  if (trailing && !/[?.!]$/.test(out)) out += trailing[0];
  return out;
}

const sets = fs
  .readdirSync(VOCAB_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

const missing = new Set();
let totalAdded = 0;

for (const slug of sets) {
  const file = path.join(VOCAB_DIR, slug, "index.json");
  if (!fs.existsSync(file)) continue;
  const data = JSON.parse(fs.readFileSync(file, "utf8"));
  let added = 0;
  for (const w of data.words ?? []) {
    if (!w.en) {
      const en = lookup(w.id);
      if (en) {
        w.en = en;
        added++;
      } else {
        missing.add(w.id);
      }
    }
  }
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
  console.log(`${slug}: ${added} translations added (total ${data.words.length})`);
  totalAdded += added;
}

console.log(`\nTOTAL added: ${totalAdded}`);
if (missing.size) {
  console.log(`\nMISSING (${missing.size}):`);
  for (const m of [...missing].sort()) console.log("  " + m);
}
